name: Maven Package

# ✅ This is where the permissions go
permissions:
  contents: read
  id-token: write
  actions: read
  packages: write
  security-events: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Submit dependency snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
